name: pull-request

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
      - uses: actions/checkout@v2
      - name: Set up node 
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests 
        run: npm run test:watch