name: Mobile CI/CD pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
      - run: npm i
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
     
      - run: npm run test:watch
